//! Central Tauri command registration.
//!
//! Tauri allows exactly one `invoke_handler`, so every `#[tauri::command]` must
//! appear in a single `generate_handler!` list. This file is that one list -
//! kept out of `lib.rs` (the app entry point) so adding a command touches the
//! command module and this registry, not the bootstrap. The list is grouped by
//! the owning `commands::<domain>` module; order does not affect dispatch.

/// Register every command on the builder. Add new commands under their domain's
/// section below (and implement them in the matching `commands::<domain>` file).
#[allow(
    clippy::too_many_lines,
    reason = "intentionally a single flat list of every registered command"
)]
pub(crate) fn register(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {
    builder.invoke_handler(tauri::generate_handler![
        // -- connection / servers --------------------------------------
        super::connection::connect,
        super::connection::disconnect,
        super::connection::get_status,
        super::servers::list_servers,
        super::servers::get_active_server,
        super::servers::set_active_server,
        super::servers::disconnect_server,
        super::servers::find_user_by_hash,
        super::servers::find_user_in_server,
        super::server::get_server_config,
        super::server::get_server_info,
        super::server::get_welcome_text,
        super::server::ping_server,
        super::public_servers::fetch_public_servers,
        super::public_servers::fetch_file_server_capabilities,
        // -- certificates ----------------------------------------------
        super::certificates::generate_certificate,
        super::certificates::list_certificates,
        super::certificates::delete_certificate,
        super::certificates::export_certificate,
        super::certificates::import_certificate,
        super::certificates::sign_document,
        // -- channels --------------------------------------------------
        super::channels::get_channels,
        super::channels::get_users,
        super::channels::get_user_texture,
        super::channels::get_registered_user_texture,
        super::channels::release_registered_user_textures,
        super::channels::get_user_comment,
        super::channels::get_channel_description,
        super::channels::select_channel,
        super::channels::join_channel,
        super::channels::peek_pchat_channel,
        super::channels::get_current_channel,
        super::channels::toggle_listen,
        super::channels::get_listened_channels,
        super::channels::get_push_subscribed_channels,
        super::channels::get_unread_counts,
        super::channels::mark_channel_read,
        super::channels::update_channel,
        super::channels::create_channel,
        super::channels::delete_channel,
        // -- messaging -------------------------------------------------
        super::messaging::get_messages,
        super::messaging::send_message,
        super::messaging::edit_message,
        super::messaging::send_read_receipt,
        super::messaging::query_read_receipts,
        super::messaging::send_typing_indicator,
        super::messaging::send_watch_sync,
        super::messaging::send_draw_stroke,
        super::messaging::request_link_preview,
        super::messaging::send_reaction,
        super::messaging::pin_message,
        super::messaging::delete_pchat_messages,
        super::messaging::plugin_inject_chat_message,
        super::messaging::plugin_update_chat_message,
        super::messaging::super_search,
        super::messaging::get_photos,
        // -- direct messages -------------------------------------------
        super::dm::send_dm,
        super::dm::get_dm_messages,
        super::dm::select_dm_user,
        super::dm::get_dm_unread_counts,
        super::dm::mark_dm_read,
        // -- realtime --------------------------------------------------
        super::realtime::send_push_update,
        super::realtime::send_subscribe_push,
        super::realtime::send_webrtc_signal,
        // -- audio / voice ---------------------------------------------
        super::audio::get_audio_devices,
        super::audio::get_output_devices,
        super::audio::get_audio_settings,
        super::audio::get_denoiser_param_specs,
        super::audio::get_available_denoiser_algorithms,
        super::audio::set_audio_settings,
        super::audio::set_audio_backend,
        super::audio::get_audio_backend,
        super::audio::probe_microphone,
        super::audio::get_capture_state,
        super::audio::get_voice_state,
        super::audio::enable_voice,
        super::audio::enable_voice_muted,
        super::audio::disable_voice,
        super::audio::toggle_mute,
        super::audio::toggle_deafen,
        super::audio::push_to_talk_start,
        super::audio::push_to_talk_end,
        super::audio::voice_priority_start,
        super::audio::voice_priority_end,
        super::audio::set_user_volume,
        super::audio::start_mic_test,
        super::audio::stop_mic_test,
        super::audio::calibrate_voice_threshold,
        super::audio::start_voice_replay,
        super::audio::stop_voice_replay,
        super::audio::start_latency_test,
        super::audio::stop_latency_test,
        super::audio::start_recording,
        super::audio::stop_recording,
        super::audio::get_recording_state,
        // -- profile ---------------------------------------------------
        super::profile::set_user_comment,
        super::profile::set_user_texture,
        super::profile::get_own_session,
        super::profile::send_plugin_data,
        super::profile::send_plugin_message,
        super::profile::send_fancy_poll,
        super::profile::send_fancy_poll_vote,
        // -- files / file-server ---------------------------------------
        super::files::upload_file,
        super::files::upload_bytes,
        super::files::upload_binary,
        super::files::cancel_upload,
        super::files::download_file,
        super::files::download_to_base64,
        super::files::fileserver_admin_list_files,
        super::files::fileserver_admin_list_documents,
        super::files::fileserver_admin_list_calendars,
        super::files::fileserver_admin_delete_file,
        super::files::fileserver_admin_delete_document,
        super::files::fileserver_admin_file_base64,
        super::files::fileserver_my_list_files,
        super::files::fileserver_my_delete_file,
        super::files::fileserver_my_file_base64,
        super::files::fileserver_my_file_link,
        super::files::fileserver_get_private,
        super::files::fileserver_put_private,
        super::files::save_markdown_file,
        super::files::add_custom_emote,
        super::files::remove_custom_emote,
        super::files::write_translation_files,
        super::files::check_files_exist,
        // -- offload (message paging) ----------------------------------
        super::offload::offload_message,
        super::offload::load_offloaded_message,
        super::offload::load_offloaded_messages_batch,
        super::offload::clear_offloaded_messages,
        super::offload::fetch_older_messages,
        super::offload::get_debug_stats,
        // -- admin / moderation ----------------------------------------
        super::admin::kick_user,
        super::admin::ban_user,
        super::admin::register_user,
        super::admin::mute_user,
        super::admin::deafen_user,
        super::admin::set_priority_speaker,
        super::admin::reset_user_comment,
        super::admin::remove_user_avatar,
        super::admin::move_user_to_channel,
        super::admin::move_channel_users,
        super::admin::request_user_stats,
        super::admin::request_user_list,
        super::admin::update_user_list,
        super::admin::request_user_comment,
        super::admin::request_ban_list,
        super::admin::update_ban_list,
        super::admin::request_acl,
        super::admin::update_acl,
        // -- key sharing (pchat custodians) ----------------------------
        super::keyshare::confirm_custodians,
        super::keyshare::accept_custodian_changes,
        super::keyshare::approve_key_share,
        super::keyshare::dismiss_key_share,
        super::keyshare::query_key_holders,
        super::keyshare::get_key_holders,
        super::keyshare::key_takeover,
        // -- onboarding ------------------------------------------------
        super::onboarding::get_onboarding_config,
        super::onboarding::get_onboarding_response,
        super::onboarding::save_onboarding_config,
        super::onboarding::submit_onboarding_response,
        super::onboarding::request_onboarding_response,
        // -- server settings / plugin admin ----------------------------
        super::audit::get_audit_config,
        super::audit::query_audit_log,
        super::audit::request_audit_config,
        super::audit::save_audit_config,
        super::server_settings::get_server_settings,
        super::server_settings::save_server_settings,
        // -- account (self-service) ------------------------------------
        super::account::get_account_settings,
        super::account::update_account_settings,
        super::plugin_admin::get_plugin_registry,
        super::plugin_admin::get_plugin_broadcasts,
        super::plugin_admin::request_server_plugins,
        super::plugin_admin::set_server_plugin_enabled,
        super::plugin_admin::install_server_plugin,
        super::plugin_admin::uninstall_server_plugin,
        super::plugin_admin::fetch_plugin_manifest_sha256,
        super::plugin_admin::fetch_marketplace_index,
        super::plugin_admin::fetch_marketplace_plugin,
        super::plugin_info::decode_plugin_info,
        // -- images ----------------------------------------------------
        super::image::blur_image,
        super::image::process_background,
        // -- popouts / overlays / window -------------------------------
        super::popout::open_image_popout,
        super::popout::take_popout_image,
        super::popout::open_stream_popout,
        super::popout::take_popout_stream,
        super::popout::open_dm_popout,
        super::popout::take_popout_dm,
        super::popout::open_translation_popout,
        super::draw_overlay::open_drawing_overlay,
        super::draw_overlay::close_drawing_overlay,
        super::draw_overlay::take_drawing_overlay_context,
        super::window::set_window_aspect_ratio,
        // -- system / diagnostics --------------------------------------
        super::system::reset_app_data,
        super::system::set_log_level,
        super::system::set_log_to_file,
        super::system::set_terminal_logging,
        super::system::set_auto_zip_logs,
        super::system::get_log_directory,
        super::system::export_logs,
        super::system::set_notifications_enabled,
        super::system::set_disable_dual_path,
        super::system::update_badge_count,
        super::system::get_system_clock_format,
        // -- interface mode (full vs. minimal qt6ui client) --------------
        super::ui_mode::get_ui_mode,
        super::ui_mode::set_ui_mode,
        super::ui_mode::get_system_specs,
        super::ui_mode::relaunch_in_minimal_mode,
        // -- screen sharing (broadcasting is desktop-only; viewing works
        //    everywhere via the webview viewer + send_webrtc_signal) ----
        #[cfg(not(target_os = "android"))]
        super::screenshare::list_capture_sources,
        #[cfg(not(target_os = "android"))]
        super::screenshare::capture_source_thumbnail,
        #[cfg(not(target_os = "android"))]
        super::screenshare::start_screen_broadcast,
        #[cfg(not(target_os = "android"))]
        super::screenshare::stop_screen_broadcast,
        #[cfg(not(target_os = "android"))]
        super::screenshare::screen_share_capabilities,
        #[cfg(not(target_os = "android"))]
        super::screenshare::request_camera_access,
        // Real on Linux + Windows, loud stubs elsewhere (Android included).
        super::stream_view::start_native_stream_view,
        super::stream_view::stop_native_stream_view,
        super::stream_view::request_stream_keyframe,
        super::stream_view::native_stream_view_stats,
        // -- updater (desktop only) ------------------------------------
        #[cfg(not(target_os = "android"))]
        crate::updater::commands::updater_check,
        #[cfg(not(target_os = "android"))]
        crate::updater::commands::updater_pending,
        #[cfg(not(target_os = "android"))]
        crate::updater::commands::updater_download_and_install,
        #[cfg(not(target_os = "android"))]
        crate::updater::commands::updater_dismiss,
        #[cfg(not(target_os = "android"))]
        crate::updater::commands::updater_set_auto_install,
        #[cfg(not(target_os = "android"))]
        crate::updater::commands::updater_set_skipped_version,
    ])
}
